language: node_js
node_js:
  - '11'
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
after_script:
  - cd ./dist
  - git init
  - git config user.name "moyi"
  - git config user.email "tantaiqiuyue@gmail.com"
  - git add -A
  - git commit -m "Update document"
  - git push --force  --quiet "https://${GH_TOKEN}@github.com/tantaiMoon/rc-ts-webpack.git" master:gh-pages
# branches:
#   only:
#     - main
