language: node_js
node_js:
  - '11'
install:
  - npm install
after_script:
  - cd ./dist
  - git init
  - git config user.name "moyi"
  - git config user.email "tantaiqiuyue@gmail.com"
  - git add -A
  - git commit -m "Update document"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" "master:gh-pages"
branches:
  only:
    - master
